// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package internal

import (
	"context"
)

const pGAdvisoryLock = `-- name: PGAdvisoryLock :exec
SELECT pg_advisory_lock($1)
`

func (q *Queries) PGAdvisoryLock(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, pGAdvisoryLock, key)
	return err
}

const pGAdvisoryUnlock = `-- name: PGAdvisoryUnlock :exec
SELECT pg_advisory_unlock($1)
`

func (q *Queries) PGAdvisoryUnlock(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, pGAdvisoryUnlock, key)
	return err
}
